data:
  AzureWebJobsStorage: QWNjb3VudE5hbWU9ZGV2c3RvcmVhY2NvdW50MTtBY2NvdW50S2V5PUVieTh2ZE0wMnhOT2NxRmxxVXdKUExsbUV0bENEWEoxT1V6RlQ1MHVTUlo2SUZzdUZxMlVWRXJDejRJNnRxL0sxU1pGUFRPdHIvS0JIQmVrc29HTUd3PT07RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHA7QmxvYkVuZHBvaW50PWh0dHA6Ly9ob3N0LmRvY2tlci5pbnRlcm5hbDoxMDAwMC9kZXZzdG9yZWFjY291bnQxO1F1ZXVlRW5kcG9pbnQ9aHR0cDovL2hvc3QuZG9ja2VyLmludGVybmFsOjEwMDAxL2RldnN0b3JlYWNjb3VudDE7VGFibGVFbmRwb2ludD1odHRwOi8vaG9zdC5kb2NrZXIuaW50ZXJuYWw6MTAwMDIvZGV2c3RvcmVhY2NvdW50MTs=
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRefName }}